# Generated by Django 4.1 on 2023-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
                (
                    "id_document",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/user_requests/"
                    ),
                ),
                (
                    "proof_of_employment",
                    models.FileField(
                        blank=True, null=True, upload_to="images/user_requests/"
                    ),
                ),
            ],
        ),
    ]
