# Generated by Django 4.1 on 2023-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_key",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
