# Generated by Django 4.1 on 2023-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_user_auth_key_authkeys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authkeys",
            name="auth_key",
        ),
        migrations.AddField(
            model_name="authkeys",
            name="authkey",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
