# Generated by Django 4.1 on 2023-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_authkeys_auth_key_authkeys_authkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authkeys",
            name="authkey",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
