# Generated by Django 4.1 on 2023-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_authkeys_authkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=50,
            ),
        ),
    ]
