# Generated by Django 4.1 on 2023-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_key",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
