# Generated by Django 4.1 on 2023-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_course_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
