# Generated by Django 4.1 on 2023-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_registration_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="level",
            field=models.CharField(
                choices=[
                    ("First Year", "1"),
                    ("Second Year", "2"),
                    ("Third Year", "3"),
                    ("4th Year", "4"),
                ],
                default="First Year",
                max_length=50,
            ),
        ),
    ]
