# Generated by Django 4.1 on 2023-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_query_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
