# Generated by Django 4.1 on 2023-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_module_code_alter_module_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
