# Generated by Django 4.1 on 2023-06-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.module",
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="question_text",
            field=models.TextField(max_length=200),
        ),
    ]
