# Generated by Django 4.1 on 2023-06-26 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_query_module_alter_query_pub_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="question_text",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
