# Generated by Django 4.1 on 2023-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_query_user_alter_query_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="question_text",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
