# Generated by Django 4.1 on 2023-06-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_alter_query_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.course",
            ),
        ),
    ]
