# Generated by Django 4.1 on 2023-06-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="module",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.query",
            ),
        ),
    ]
