# Generated by Django 4.1 on 2023-06-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_rename_question_answer_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="dashboard.query",
            ),
        ),
    ]
