# Generated by Django 4.1 on 2023-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_alter_answer_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/user_profile_pictures/"
            ),
        ),
    ]
