# Generated by Django 4.1 on 2023-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureprofile",
            name="receive_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="receive_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="receive_emails",
            field=models.BooleanField(default=False),
        ),
    ]
