# Generated by Django 4.1 on 2023-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_user_is_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggedTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField(max_length=150)),
            ],
        ),
    ]
