# Generated by Django 4.1 on 2023-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_loggedticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedticket",
            name="resolve",
            field=models.BooleanField(default=False),
        ),
    ]
