# Generated by Django 4.1 on 2023-11-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_alter_user_profile_pic_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="votes",
        ),
        migrations.AddField(
            model_name="vote",
            name="query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_votes",
                to="dashboard.query",
            ),
        ),
    ]
