# Generated by Django 4.1 on 2023-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_remove_query_votes_remove_vote_votes_vote_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("UP", "Upvote"), ("DOWN", "Downvote")],
                default="UP",
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "query", "answer")},
        ),
    ]
