# Generated by Django 4.1 on 2023-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_rename_date_time_notification_date_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category_icon",
            field=models.CharField(
                choices=[
                    (
                        "<i class='bi bi-exclamation-circle text-warning'></i>",
                        "Warning",
                    ),
                    ("<i class='bi bi-x-circle text-danger''></i>", "Danger"),
                    ("<i class='bi bi-check-circle text-success'></i>", "Success"),
                    ("<i class='bi bi-info-circle text-primary'></i>", "Info"),
                ],
                default="<i class='bi bi-check-circle text-success'></i>",
                max_length=200,
            ),
        ),
    ]
