# Generated by Django 4.1 on 2023-11-22 19:23

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_notification_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=dashboard.models.registration_directory_path,
            ),
        ),
    ]
