# Generated by Django 4.1 on 2023-11-23 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_remove_learningmaterial_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmaterial",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_learning_materials",
                to="dashboard.module",
            ),
        ),
    ]
