# Generated by Django 4.1 on 2023-11-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0040_alter_learningmaterial_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmaterial",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("AUDIO", "Audio"),
                    ("VIDEO", "Video"),
                    ("DOCUMENT", "Document"),
                    ("OTHER", "Other"),
                ],
                default="IMAGE",
                max_length=200,
            ),
        ),
    ]
